### ISSUE TITLE
按照 readme 无法正常启动

### ISSUE THREAD

**Issue by hunter-valley** [howie6879/novels-search#1]
python 小白，不是很懂，原本准备自己造一个小说采集器，故找到了这个项目

环境是 ubuntu，安装了 python3，通过如下的命令启动
启动命令：python3 novels_search/server.py

2017-04-05 03:57:05,659 WARNING aiocache.log(13) | cPickle module not found, using pickle
Traceback (most recent call last):
  File "novels_search/server.py", line 12, in <module>
    from novels_search.views.novels_blueprint import novels_bp
ImportError: No module named 'novels_search'

**安装模块的时候，是不是哪里不对，没安装成功**
root@localhost:~/novels-search# python3 setup.py install
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.5/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing novels_search.egg-info/PKG-INFO
writing dependency_links to novels_search.egg-info/dependency_links.txt
writing top-level names to novels_search.egg-info/top_level.txt
reading manifest file 'novels_search.egg-info/SOURCES.txt'
writing manifest file 'novels_search.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying novels_search.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying novels_search.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying novels_search.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying novels_search.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/novels_search-0.0.0-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing novels_search-0.0.0-py3.5.egg
Removing /usr/local/lib/python3.5/dist-packages/novels_search-0.0.0-py3.5.egg
Copying novels_search-0.0.0-py3.5.egg to /usr/local/lib/python3.5/dist-packages
novels-search 0.0.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.5/dist-packages/novels_search-0.0.0-py3.5.egg
Processing dependencies for novels-search==0.0.0
Finished processing dependencies for novels-search==0.0.0

**Comment by howie6879** [comment]
你好，本项目是提供小说在线搜索解析，根据你目前情况

**Comment by hunter-valley** [comment]
已经能正常使用了，不过我并没有运行这句：
gunicorn --bind localhost:8000 --worker-class sanic_gunicorn.Worker server:app

**Comment by howie6879** [comment]
能正常使用就好，那句是另外一种启动方式，二选一即可。
有问题及时反馈^_^
